   <div class="header-warp">
    <div class="header">
     <div class="inner">
        <div class="float-left">
        <span class="head-brand">
            数据平台
        </span>
        <div class="head-menu">
          <a class="menu-item active">
             表单
          </a>
          <a class="menu-item">
             表单
          </a>
        </div>
        <div class="head-search-box">
             <input type="text" class="search-hide" id="h-search-text" required/>
             <span class="iconfont icon-sousuo"></span>
        </div>
        </div>
        <div class="float-right">
        <div class="head-user-info">
            <span class="iconfont icon-xinxi message"></span>
            <div class="user-head-box">
                <img class="user-head-img"/>
                <span class="iconfont icon-jiantou arrows"></span>
            </div>
        </div>
        </div>
    </div>
    </div>
    <div class="navigation">
       <h1 class="module-name">
       <span class="name">海外华人小孩学中文福利包</span>
       <div class="module-setting-box">
         <span class="iconfont icon-shezhi3 setting-icon"></span>
         <div class="module-setting-hide">
            <p class="item">
              <i class="iconfont icon-fuzhi"></i>
              <em>复制</em>
            </p>
            <p class="item disable">
             <i class="iconfont icon-yidongyema"></i>
             <em>移动到</em>
             <i class="iconfont icon-jiantou1 arrows"></i>
            </p>
         </div>
       </div>
       </h1>
       <div class="module-action">

          <div class="action-left">
            <a class="item active">概述</a>
            <a class="item">数据数据</a>
            <a class="item">发布</a>
          </div>
          <div class="action-right">
             <em class="name">发布表单</em>
             <input type="text" value="" class="form-link-text" readonly="readonly"/>
             <span class="iconfont icon-fuzhi" id="copy-form-link"></span>
             <span class="hover-code-show iconfont icon-erweima"></span>
             <button class="form-publish" id="form-publish">发布</button>
          </div>
       </div>
    </div>
 </div>